### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by baskerville** [falconindy/expac#14]
If `cower-git` is installed on my system, the following command: `expac -Q %v cower` outputs the version of `cower-git`.

**Comment by rmarquis** [comment]
FYI, it seems a [recent patch](https://lists.archlinux.org/pipermail/pacman-dev/2016-April/021005.html) on the mailing list is modifying the way pacman queries providers.

I'm not sure if it would actually be relevant to revert to the old behavior to match the new behavior here.
