### ISSUE TITLE
expac produces empty output

### ISSUE THREAD

**Issue by imran27** [falconindy/expac#27]
I use the expac-git from AUR and it is updated to it's latest revision. I have tried the examples and nothing works. All the expac commands produce empty output. The same happens with the stable version too.

**Comment by falconindy** [comment]
What does your /etc/pacman.conf look like? What does strace show?

**Comment by imran27** [comment]
Here's my pacman.conf
[pacman.conf.txt](https://github.com/falconindy/expac/files/208766/pacman.conf.txt)

How to do strace?

**Comment by falconindy** [comment]
Thanks, fixed in a410da86641d0e0d7af92098602645dfa40c8bbc

**Comment by imran27** [comment]
Great, it works now
