### ISSUE TITLE
add versioned provisions support

### ISSUE THREAD

**Issue by rmarquis** [falconindy/expac#32]
Consider the following:

```
$ sudo pacman -S "expac>7"
warning: expac-8-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Package (1)  Old Version  New Version  Net Change  Download Size

extra/expac  8-1          8-1            0.00 MiB       0.01 MiB

Total Download Size:   0.01 MiB
Total Installed Size:  0.03 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] n
```

```
$ sudo pacman -S "expac>8"
error: target not found: expac>8
```

Using expac:
```
$ expac -S '%r/%n-%v' expac
extra/expac-8-1
$ expac -S '%r/%n-%v' "expac>7"
(no result)
```

It would be useful to have a similar versining support in expac, as this might avoid the need to do some extra check separately before using expac. Hopefully this is in the scope of expac.

In my [local fork](https://github.com/rmarquis/expac/commit/c4af19a6671ad9b6161730ed409d60aebbed901d), I've replaced `alpm_db_get_pkg()` with `alpm_find_dbs_satisfier()` when searching for exact packages, which gives the following results:

```
$ ./expac -Q '%r/%n-%v' "expac>8"
(no result, as expected)
$ ./expac -Q '%r/%n-%v' "expac>7"
local/expac-8-1
```

```
$ ./expac -S '%r/%n-%v' "expac>8"
(no result, as expected)
$ ./expac -S '%r/%n-%v' "expac>7"
extra/expac-8-1
extra/expac-8-1
```

It works, but for `-S`, the output is doubled - and I cannot find out the reason. Any idea?

I've tried passing `r->next` instead of `r`, but while the issue is fixed with `-S`, this breaks `-Q`.

**Comment by falconindy** [comment]
Even stranger for me...

```sh
./expac -S '%r/%n-%v' "expac>7"                                                                                                                                                                              
extra/expac-8-1 
extra/expac-8-1 
extra/expac-8-1 
extra/expac-8-1 
extra/expac-8-1 
extra/expac-8-1 
extra/expac-8-1 
extra/expac-8-1 
```

It seems to have something to do with the number of enabled repos which might indicate a bug in your patch somewhere.

Also, it's a shame that your patch makes "search_exact" not so exact anymore...

**Comment by falconindy** [comment]
Ah, I see. You want `alpm_find_satisfier` not `alpm_dbs_find_satisfier`.

```sh
$ ./expac -S '%r/%n-%v' "expac>7"
extra/expac-8-1
```

**Comment by rmarquis** [comment]
I'm closing this ticket - pacsift actually provides a similar feature, so no need to change semantics here.
