### ISSUE TITLE
%R provides "replaces" without versioning

### ISSUE THREAD

**Issue by polygamma** [falconindy/expac#34]
e.g. `expac -S "%n - %R" bluez-utils` yields `bluez-utils - bluez-hcidump  bluez` whereas https://www.archlinux.org/packages/extra/x86_64/bluez-utils/ lists the replacements as `bluez<=4.101, bluez-hcidump`, notice the missing `<=4.101` for `bluez`.

Would it be possible, to append the versioning, too? I would really appreciate that.

**Comment by falconindy** [comment]
Thanks

**Comment by polygamma** [comment]
Thanks for merging! :)
