### ISSUE TITLE
Add a --dbpath option

### ISSUE THREAD

**Issue by gtnuux** [falconindy/expac#41]
It would be handy if expac supported a --dbpath option like pacman does.  Currently, the only option is to create an alternative config file and then use the --config option.  This option would be especially useful for distributions, such as Manjaro, which by default keep a separate up-to-date sync database so that you can view the update-able packages without executing the dreaded 'pacman -Sy' command.

This would be a fairly trivial change.  I'd be happy to submit a pull request if you think it might be be a worthwhile addition.

-Jeff

**Comment by falconindy** [comment]
There's already an option to consume a different pacman.conf. I think that's the right level of granularity to support.
