### ISSUE TITLE
'expac -s target' goes through all installed packages

### ISSUE THREAD

**Issue by drws** [falconindy/expac#43]
I can't get the search function to work with the local query. `expac -s target` (or `expac -Qs target`) goes through all local (installed) packages.

I'm using the latest release 10. Is this a bug or am I doing it wrong?

**Comment by falconindy** [comment]
I don't really understand the problem here. The local db only has installed packages. What are you trying to do?

**Comment by drws** [comment]
After rereading the manpage after some time I've found an error in my understanding of input syntax with this switch (as predicted in OP...). Sorry for the confusion, closing this up.
